### ISSUE TITLE
Inconsistent use of "ext" in IFU bad pixel correction

### ISSUE THREAD

**Issue by DFEvans** [avigan/VLTPF#48]
In sph_ifs_fix_badpix, there is some confusion between whether the region to be searched is from -ext to +ext+1, or -ext//2 to +ext//2+1. Most of the code uses the former, but the definitions of sub_low and sub_high use the latter, leading to inconsistent array lengths and an error.

Can be fixed by removing the "//2" on lines 217 and 218 of IFS.py, assuming that gives the desired definition.

**Comment by avigan** [comment]
I will look into this issue more closely because this is a sensitive method that took a long time to optimise.
