### ISSUE TITLE
Possible optimisations for sigma_filter

### ISSUE THREAD

**Issue by DFEvans** [avigan/VLTPF#49]
Two possible optimisations for sigma_filter in imutils.py:

1. scipy's uniform_filter() is about 4x faster than astropy's Box2DKernel and convolve(). Using uniform_filter's "constant" mode (i.e. zero padding), the two agree to about ~1e-13. The replacement would be as follows:
```
# Current
    box2 = box**2

    kernel = Box2DKernel(box)
    img_clip = (convolve(img, kernel)*box2 - img) / (box2-1)

    imdev = (img - img_clip)**2
    fact = nsigma**2 / (box2-2)
    imvar = fact*(convolve(imdev, kernel)*box2 - imdev)

# Replacement
    from scipy.ndimage.filter import uniform_filter

    box2 = box**2

    img_clip = (uniform_filter(img, box, mode = "constant")*box2 - img)/(box2-1)

    imdev = (img - img_clip)**2
    fact = nsigma**2 / (box2-2)
    imvar = fact*(uniform_filter(imdev, box, mode = "constant")*box2 - imdev)
```

2. I think it's safe to assume that if one iteration of sigma clipping does not clip any values, then no future iteration will ever do so, because each is passing the same, unchanged input to the next iteration. I've found this typically cuts the number of iterations in half. One can check if any pixels are changed with:
```
    nchange = img.size - nok
    if (iterate is True):
        _iters = _iters+1
        if (_iters >= max_iter) or nchange == 0:
            # return...
```

**Comment by avigan** [comment]
Thanks a lot for the suggestions! It is indeed a bit faster with uniform_filter()

**Comment by avigan** [comment]
Reopening the issue because in fact `scipy.ndimage.uniform_filter()` does not support NaN. More tests needed to determine if hiding NaN + uniform_filter() + restoring NaN is actually faster than Box2DKernel + convolve()
