### ISSUE TITLE
Weird behavior in star_centers_from_waffle_cube

### ISSUE THREAD

**Issue by m-samland** [avigan/VLTPF#56]
I tried using the star_centers_from_waffle_cube routine from toolbox.py on some IRDIS data I have (after cropping the images in two halves, like VLTPF does). It worked fine and found the centers, and confirming the output plots yielded the right positions, but the center_guess boxes where relative bad, as in only half of spots in the box in some cases. Using the best fit position output of the first fit, as "center_guess" leads to some fits completely failing. The two files attached show the results:
Default: 
center_guess = np.array(((485, 520), (486, 508)))
And the refined position:
center_guess = np.array(((480, 525), (483, 511)))

[center_test_default.pdf](https://github.com/avigan/VLTPF/files/1821863/center_test_default.pdf)
[center_test_better_guess.pdf](https://github.com/avigan/VLTPF/files/1821867/center_test_better_guess.pdf)

Hope you can help!

**Comment by avigan** [comment]
Have you tried with clean images? The ones you show are full of uncorrected bad pixels. It may bias the estimation.
