### ISSUE TITLE
IRDIS reduction crash when only SKY files are present

### ISSUE THREAD

**Issue by sylacour** [avigan/VLTPF#58]
Hello Arthur

So I have the following crash:

>>> dataset.full_reduction()
*
* Full IRDIS reduction at path /Users/slacour/DATA/SPHERE/SEARCH/downloadFiles/sphere_irdifs_HIP_32775_BB-H_id=200412632/2016-12-11/IRDIS/
*

Sorting raw files
 * found 10 FITS files in /Users/slacour/DATA/SPHERE/SEARCH/downloadFiles/sphere_irdifs_HIP_32775_BB-H_id=200412632/2016-12-11/IRDIS/raw/
Extracting frames information
Traceback (most recent call last):

  File "<ipython-input-3-a4db03edfbfe>", line 1, in <module>
    dataset.full_reduction()

  File "/Users/slacour/ONGOING/SPHERE/VLTPF/vltpf/SPHERE.py", line 456, in full_reduction
    r.full_reduction()

  File "/Users/slacour/ONGOING/SPHERE/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 287, in full_reduction
    self.init_reduction()

  File "/Users/slacour/ONGOING/SPHERE/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 215, in init_reduction
    self.sort_frames()

  File "/Users/slacour/ONGOING/SPHERE/VLTPF/vltpf/IRDIS/ImagingReduction.py", line 507, in sort_frames
    toolbox.compute_times(frames_info)

  File "/Users/slacour/ONGOING/SPHERE/VLTPF/vltpf/toolbox.py", line 103, in compute_times
    ts_start = time_start + time_delta * idx

TypeError: ufunc multiply cannot use operands with types dtype('<m8[ns]') and dtype('O')

---> I have linked it to the fact that there are only SKY frames in the raw directory:

files_info['DPR CATG']
Out[28]: 
FILE
SPHER.2016-12-12T07:03:53.315    SCIENCE
SPHER.2016-12-12T07:05:06.809    SCIENCE
SPHER.2016-12-12T07:06:20.299    SCIENCE
SPHER.2016-12-12T09:51:03.346      CALIB
SPHER.2016-12-12T09:51:25.697      CALIB
SPHER.2016-12-12T09:51:57.159      CALIB
SPHER.2016-12-12T09:52:39.344      CALIB
SPHER.2016-12-12T09:53:30.411      CALIB
SPHER.2016-12-12T09:55:04.403      CALIB
SPHER.2016-12-12T12:02:20.467      CALIB
Name: DPR CATG, dtype: object

files_info['DPR TYPE']
Out[29]: 
FILE
SPHER.2016-12-12T07:03:53.315                SKY
SPHER.2016-12-12T07:05:06.809                SKY
SPHER.2016-12-12T07:06:20.299                SKY
SPHER.2016-12-12T09:51:03.346          FLAT,LAMP
SPHER.2016-12-12T09:51:25.697          FLAT,LAMP
SPHER.2016-12-12T09:51:57.159          FLAT,LAMP
SPHER.2016-12-12T09:52:39.344          FLAT,LAMP
SPHER.2016-12-12T09:53:30.411          FLAT,LAMP
SPHER.2016-12-12T09:55:04.403               DARK
SPHER.2016-12-12T12:02:20.467    DARK,BACKGROUND
Name: DPR TYPE, dtype: object

**Comment by avigan** [comment]
I downloaded this public dataset: the problem is that you have no actual science files except for the SKY frames! I will raise an error in such cases.
