### ISSUE TITLE
Typos in IFS.py "HIERARCH ESO INS4 DROT3 BEGIN" keywords

### ISSUE THREAD

**Issue by Rumpelstil** [avigan/VLTPF#92]
In IFS.py, the following lines should be made consistent, i.e. fix typos ("INS3" -> "INS4", ...)

                elif k == 'HIERARCH ESO INS4 DROT3 BEGIN':
                    # in June 2021 ESO changed INS4 DROT3 BEGIN to INS4 DROT3 START
                    v_begin = hdr.get('HIERARCH ESO INS3 DROT2 BEGIN')
                    v_start = hdr.get('HIERARCH ESO INS3 DROT2 START')

**Comment by avigan** [comment]
Thanks @Rumpelstil for the bug report. Issue fixed in commit 1e60094 in the `develop` branch. Correction will be included in next release.
