### ISSUE TITLE
Typo in IFS.py / sph_ifs_cal_wave for mode OBS_H -> wavelength recalibration too "blue" in H-band

### ISSUE THREAD

**Issue by Rumpelstil** [avigan/VLTPF#93]
In IFS.py /  `def sph_ifs_cal_wave(self, silent=True) ` for `mode =='OBS_H' `only the first 3 calibration lines are considered for the wavelength recalibration. The wavelength scale thus is shifted too much to the blue at the red edge of the spectrum.
`        elif mode == 'OBS_H':
            args = ['esorex',
                    '--no-checksum=TRUE',
                    '--no-datamd5=TRUE',
                    'sph_ifs_wave_calib',
                    '--ifs.wave_calib.number_lines=3',`

Suggested fix:
`                    '--ifs.wave_calib.number_lines=4',
`

**Comment by avigan** [comment]
Now fixed in 3f6a6e9.
