### ISSUE TITLE
IFS.py / wavelength_optimisation - unit mismatch in call

### ISSUE THREAD

**Issue by Rumpelstil** [avigan/VLTPF#95]
There is a unit mismatch in IFS.py / sph_ifs_wavelength_recalibration in the call 
`      res = optim.minimize(wavelength_optimisation, 0.9, method='Nelder-Mead',
                             args=(wave_scale, wave_lasers, peak_position_lasers))`

"wave_ref" (set to '0.9' in the call), and subsequently "wave" and "wave_peaks" are in units of micrometer. 
"wave_lasers" is in units of nm. 

In the example tested, the optimisation routine is sufficiently robust to converge on wave_ref = 963.75..., but requires about twice as many iterations compared to using wave_ref = 900 (or 950) as a starting value.

Suggested fix:

`      res = optim.minimize(wavelength_optimisation, 950., method='Nelder-Mead',
                             args=(wave_scale, wave_lasers, peak_position_lasers))`

**Comment by avigan** [comment]
Thanks @Rumpelstil for bug report. The issue was introduced at some point when I switched from wavelength units in micron to nanometers. Issue now fixed in 9d9d313.
