### ISSUE TITLE
More information about needed data

### ISSUE THREAD

**Issue by liafsartori** [avigan/VLTPF#96]
Hi, would it be possible to have more information about the data needed in for IFS.Reduction and how to name them ('/Users/avigan/data/sphere-test-target/IFS/' in the example code)? Can we directly use the data downloaded by the ESO archive? And should we use the processed or raw calibration data? Thank you very much!

**Comment by Rumpelstil** [comment]
From the ESO archive, you need to request the _raw science_ plus the _associated raw calibration_ files. For one particular data set, I had in addition to find and download a DIT=1.65s dark. All the files should be copied to a subdirectory "raw", e.g. /Users/avigan/data/sphere-test-target/IFS/raw  

After completion, the reduced data can be found in the subdirectory "products". Temporary directories are deleted by the "cleaning" command (last step in the example). If you comment this out, it gives you access to calibration data etc.

**Comment by liafsartori** [comment]
Thank you very much!

**Comment by avigan** [comment]
I guess this is direct relation with issue #24, which concerns writing a proper documentation. This is a long overdue task.
